version: '3'

services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_MASTER_KEY=masterkey
      - MEILI_NO_ANALYTICS=true
    ports:
      - 7700:7700
    volumes:
      - meilidata:/data.ms
    restart: unless-stopped

volumes:
  meilidata: